name: Publish Package

on:
  push:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Bump version to tag
      run: mvn -B --file pom.xml versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get the artifact name
      id: artifact
      run: echo ::set-output name=ARTIFACT::cassandra-external-file-seed-provider-${{ steps.get_version.outputs.VERSION }}.jar

    - name: Compute checksum
      run: cd target; sha256sum ${{ steps.artifact.outputs.ARTIFACT }} > SHA256SUMS

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload JAR
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/${{ steps.artifact.outputs.ARTIFACT }}
        asset_name: ${{ steps.artifact.outputs.ARTIFACT }}
        asset_content_type: application/java-archive

    - name: Upload checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/SHA256SUMS
        asset_name: SHA256SUMS
        asset_content_type: text/plain
